replicaCount: 1

image:
  repository: raman83/auth-switch-service
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

ingress:
  enabled: false  # Set true later if you want to expose via Ingress

env:
  - name: SPRING_PROFILES_ACTIVE
    value: prod
  - name: SPRING_CONFIG_LOCATION
    value: "file:/config/application-prod.yml"

volumeMounts:
  - name: config
    mountPath: /config
    readOnly: true

volumes:
  - name: config
    configMap:
      name: auth-switch-service-config


serviceAccount:
  create: false

autoscaling:
  enabled: false

resources: {}
