apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.db.name }}
type: Opaque
stringData:
  {{ .Values.secrets.db.usernameKey }}: {{ .Values.secrets.db.usernameValue }}
  {{ .Values.secrets.db.passwordKey }}: {{ .Values.secrets.db.passwordValue }}
