apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
      annotations:
        sidecar.istio.io/inject: "{{ .Values.istio.enabled }}"
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8081
          env:
            - name: RSA_KEYS_PATH
              value: /keys
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.profile }}"
          volumeMounts:
            - name: rsa-keys
              mountPath: /keys
              readOnly: true
      volumes:
        - name: rsa-keys
          secret:
            secretName: auth-rsa-keys
