apiVersion: v1
kind: Secret
metadata:
  name: auth-rsa-keys
type: Opaque
data:
  private.pem: {{ .Files.Get "keys/rsa_private.pem" | b64enc }}
  public.pem: {{ .Files.Get "keys/rsa_public.pem" | b64enc }}
