apiVersion: apps/v1
kind: Deployment
metadata:
  name: settlement-service
  labels:
    app: settlement-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: settlement-service
  template:
    metadata:
      labels:
        app: settlement-service
      annotations:
        sidecar.istio.io/inject: "{{ .Values.istio.enabled }}"
    spec:
      containers:
        - name: settlement-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.profile }}"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.kafka.bootstrapServers }}"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.kafka.bootstrapServers }}"

            - name: DB_HOST
              value: {{ .Values.env.database.host }}
            - name: DB_PORT
              value: "{{ .Values.env.database.port }}"
            - name: DB_NAME
              value: {{ .Values.env.database.name }}

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.db.name }}
                  key: {{ .Values.secrets.db.usernameKey }}

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.db.name }}
                  key: {{ .Values.secrets.db.passwordKey }}
          volumeMounts:
            - name: batch-dir
              mountPath: /app/batch

      volumes:
        - name: batch-dir
          hostPath:
            path: {{ .Values.batch.outputHostPath }}
            type: DirectoryOrCreate
