apiVersion: v1
kind: Service
metadata:
  name: ach-adapter-service
spec:
  selector:
    app: ach-adapter-service
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
