replicaCount: 1

image:
  repository: raman83/account-service
  tag: latest
  pullPolicy: Always

env:
  profile: prod

  
  database:
    host: host.docker.internal
    port: 5432
    name: accountsdb


secrets:
  db:
    name: accounts-db-secret
    usernameKey: db-user
    passwordKey: db-password
    usernameValue: postgres
    passwordValue: postgres

service:
  type: ClusterIP
  port: 8084

istio:
  enabled: false
