apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.username }}
  DB_PASSWORD: {{ .Values.database.password }}

  AUTH0_MGMT_CLIENT_ID: {{ .Values.auth0.mgmtClientId }}
  AUTH0_MGMT_CLIENT_SECRET: {{ .Values.auth0.mgmtClientSecret }}
  AUTH0_LOGIN_CLIENT_ID: {{ .Values.auth0.loginClientId }}
  AUTH0_LOGIN_CLIENT_SECRET: {{ .Values.auth0.loginClientSecret }}
